name: Deploy BLOG-WEBSITE

on:
  push:
    branches:
      - main   # jab bhi main branch me push hoga

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Install backend dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # 4️⃣ Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # 5️⃣ Build frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # 6️⃣ Success message
      - name: Deployment completed
        run: echo "✅ Build Successful"
